org.gradle.jvmargs=-Xmx3G -XX:+ParallelRefProcEnabled
org.gradle.caching=true

# NeoForge Properties
  neogradle.subsystems.parchment.minecraftVersion=1.21.1
  neogradle.subsystems.parchment.mappingsVersion=2024.11.17

  minecraft_version=1.21.1
  minecraft_version_range=[1.21.1]
  neo_version=21.1.80
  neo_version_range=[21.1.0,)
  loader_version_range=[1,)

# Mod Properties
  group=com.presencefootsteps
  mod_id=presencefootsteps
  displayname=Presence Footsteps
  license=MIT
  version=1.10.3+1.21.1
  authors=Hurricaaane (Ha3), Sollace, Paint_Ninja
  description=An overly complicated sound mod
  url=http://presencefootsteps.ha3.eu
